URL_MAIN_PAGE = 'https://stellarburgers.nomoreparties.site/'
URL_REGISTRATION_PAGE = 'https://stellarburgers.nomoreparties.site/register'
URL_PROFILE = 'https://stellarburgers.nomoreparties.site/account/profile'
URL_LOGIN = 'https://stellarburgers.nomoreparties.site/login'
URL_FORGOT_PASSWORD = 'https://stellarburgers.nomoreparties.site/forgot-password'
